/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Footer as PrismaFooter } from "@prisma/client";

export class FooterServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.FooterCountArgs, "select">): Promise<number> {
    return this.prisma.footer.count(args);
  }

  async footers(args: Prisma.FooterFindManyArgs): Promise<PrismaFooter[]> {
    return this.prisma.footer.findMany(args);
  }
  async footer(
    args: Prisma.FooterFindUniqueArgs
  ): Promise<PrismaFooter | null> {
    return this.prisma.footer.findUnique(args);
  }
  async createFooter(args: Prisma.FooterCreateArgs): Promise<PrismaFooter> {
    return this.prisma.footer.create(args);
  }
  async updateFooter(args: Prisma.FooterUpdateArgs): Promise<PrismaFooter> {
    return this.prisma.footer.update(args);
  }
  async deleteFooter(args: Prisma.FooterDeleteArgs): Promise<PrismaFooter> {
    return this.prisma.footer.delete(args);
  }
}
